namespace: ggservices
env: production
allowedOrigin: https://www.glynsgardeningservices.com,https://glynsgardeningservices.com
replicaCount: 1
image:
  pullPolicy: Always
storage:
  storageClass: standard
webserver:
  image:
    repository: index.docker.io/lmwcode/ggservices-frontend
    tag: v1.0.2
  port: 80
  type: NodePort
  host: www.glynsgardeningservices.com
  path: /
  pathType: Prefix
  recaptcha: 6Ldn3-0qAAAAAMWv4iekZdMl4Xrfj2Av2zEL7onD
  backendUrl: "https://api.glynsgardeningservices.com"
  applicationType: frontend
api:
  host: api.glynsgardeningservices.com
  port: 8091
  path: /api/
  pathType: Prefix
  applicationType: backend

# blue
backendServiceHost: ggservices-backend-service # Blue frontend (k get svc lmwcode-frontend-service -n lmwcode -o yaml. Selector = colour)

# green
# backendServiceHost: ggservices-backend-service-stage # Green frontend

# switch colour
# k patch svc ggservices-frontend-service -n lmwcode -p '{"spec":{"selector":{"harness.io/color":"green"}}}'
# if caching delete ingress k -n ingress-nginx delete pod -l app.kubernetes.io/name=ingress-nginx
livenessProbe:
  endpoint: /
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 30
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 15
  failureThreshold: 3
  successThreshold: 1
