namespace: ggservices
env: production
allowedOrigin: "https://www.glynsgardeningservices.com,https://glynsgardeningservices.com"
allowCredentials: false
frontend_url: https://www.glynsgardeningservices.com
replicaCount: 1
platform: linux/amd64
image:
  pullPolicy: Always
storage:
  storageClass: standard
api:
  image:
    repository: index.docker.io/lmwcode/ggservices-backend
    # tag: v.<+pipeline.sequenceId>
    # tag: <+serviceVariables.tag>
    tag: v1.0.0
  host: api.glynsgardeningservices.com
  port: 8091
  path: /api/
  type: ClusterIP
  protocol: TCP
  pathType: Prefix
  applicationType: backend
images:
  directory: images
webserver:
  host: www.glynsgardeningservices.com
smtp:
  from: noreply@glynsgardeningservices.com
  to: g.g.services@outlook.com
admin:
  email: info@lmwcode.co.uk
seedUser:
  email: warren_laura@yahoo.co.uk
livenessProbe:
  endpoint: /api/health/live
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  endpoint: /api/health/ready
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 120
  failureThreshold: 3
  successThreshold: 1
